sudo: required

env:
  - distribution: ubuntu
  - distribution: fedora
  - distribution: arch
  - distribution: debian-testing
  - distribution: debian

services:
  - docker
  
before_install:
  - ./ci/update_travis.sh

script:
  - CXX=clang++ CC=clang ./ci/compile_container.sh
  - ./ci/compile_container.sh
  - ./ci/static_analysis.sh